/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import java.awt.Graphics;

import javax.swing.JOptionPane;

import Modelo.Barrera;
import Modelo.Control;
import Modelo.ImageLoader;
import java.awt.BorderLayout;
import java.awt.Dimension;

/**
 *
 * @author juanc
 */
public class Calculo extends javax.swing.JPanel {

    Principal p;
    Control control;

    /**
     * Creates new form Calculo
     *
     * @param p
     * @param control
     */
    public Calculo(Principal p, Control control) {
        initComponents();
        jPanel1.setBackground(new Color(0,0,0,10));
        this.p = p;
        listener();
        this.control = control;
        setBackground(new Color(0,0,0,200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        labelTipoBarrera = new javax.swing.JLabel();
        cbxTipoDeBarrera = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbxDisenioParaArea = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbxImagenesPorSemana = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbxAreaAProteger = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtNombreDelArea = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        cbxVoltaje = new javax.swing.JComboBox<>();
        btnOtro = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtDistancia = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cbxFactorOcupacion = new javax.swing.JComboBox<>();

        jLabel15.setText("jLabel15");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese los siguientes datos:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sitka Text", 1, 14))); // NOI18N
        jPanel1.setDoubleBuffered(false);
        jPanel1.setName(""); // NOI18N

        jLabel2.setFont(new java.awt.Font("Sitka Text", 0, 11)); // NOI18N
        jLabel2.setText("Nombre de Barrera:");

        txtNombre.setFont(new java.awt.Font("Sitka Text", 0, 11)); // NOI18N

        labelTipoBarrera.setFont(new java.awt.Font("Sitka Text", 0, 11)); // NOI18N
        labelTipoBarrera.setText("Tipo de barrera:");
        labelTipoBarrera.setToolTipText("Ganoso de irme a dormir");

        cbxTipoDeBarrera.setFont(new java.awt.Font("Sitka Text", 0, 11)); // NOI18N
        cbxTipoDeBarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Barrera primaria", "Barrera secundaria" }));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 0, 11)); // NOI18N
        jLabel4.setText("Diseño para Área:");

        cbxDisenioParaArea.setFont(new java.awt.Font("Sitka Text", 0, 11)); // NOI18N
        cbxDisenioParaArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Controlada", "Supervisada" }));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 0, 11)); // NOI18N
        jLabel5.setText("Imágenes por semana:");

        cbxImagenesPorSemana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100", "200", "300" }));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 0, 11)); // NOI18N
        jLabel6.setText("Área a proteger:");

        cbxAreaAProteger.setFont(new java.awt.Font("Sitka Text", 0, 11)); // NOI18N
        cbxAreaAProteger.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrativa", "Casa", "Pasillo", "Baño público", "Baño personal", "Almacen", "Vestier", "Anden", "Jardin", "Calle", "Asensor", "Closet", "Sala de espera", "Otro" }));

        jLabel9.setFont(new java.awt.Font("Sitka Text", 0, 11)); // NOI18N
        jLabel9.setText("Voltaje[KV]:");

        jLabel7.setFont(new java.awt.Font("Sitka Text", 0, 11)); // NOI18N
        jLabel7.setText("Nombre del Área:");

        txtNombreDelArea.setFont(new java.awt.Font("Sitka Text", 0, 11)); // NOI18N
        txtNombreDelArea.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Sitka Text", 0, 11)); // NOI18N
        jLabel8.setText("Factor ocupacion:");

        cbxVoltaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "50", "70", "90" }));

        btnOtro.setText("...");

        jLabel10.setFont(new java.awt.Font("Sitka Text", 0, 11)); // NOI18N
        jLabel10.setText("Distancia (d) [m]: ");

        btnCalcular.setBackground(new java.awt.Color(255, 255, 255));
        btnCalcular.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/iconfinder_Check_27837.png"))); // NOI18N
        btnCalcular.setText("Calcular Blindaje");

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/iconfinder_Close_Icon_1398919.png"))); // NOI18N
        btnCancelar.setText("Cancelar");

        cbxFactorOcupacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "1/2", "1/5", "1/20", "1/40" }));
        cbxFactorOcupacion.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTipoBarrera)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreDelArea)
                    .addComponent(cbxTipoDeBarrera, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxAreaAProteger, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxFactorOcupacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOtro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCalcular)
                                .addGap(21, 21, 21)
                                .addComponent(btnCancelar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxDisenioParaArea, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cbxVoltaje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(cbxImagenesPorSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(34, 34, 34)))
                                    .addComponent(txtDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 34, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoBarrera)
                    .addComponent(cbxTipoDeBarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxAreaAProteger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOtro))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNombreDelArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(cbxFactorOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxDisenioParaArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbxImagenesPorSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxVoltaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCalcular)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOtro;
    private javax.swing.JComboBox<String> cbxAreaAProteger;
    private javax.swing.JComboBox<String> cbxDisenioParaArea;
    private javax.swing.JComboBox<String> cbxFactorOcupacion;
    private javax.swing.JComboBox<String> cbxImagenesPorSemana;
    private javax.swing.JComboBox<String> cbxTipoDeBarrera;
    private javax.swing.JComboBox<String> cbxVoltaje;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelTipoBarrera;
    private javax.swing.JTextField txtDistancia;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreDelArea;
    // End of variables declaration//GEN-END:variables
    private float factorOcupa = 0;
    private String area;
    double x;
    private CalculosRegistrados calculosRegistrados = null;
    public void listener() {
        btnCalcular.addActionListener(f -> {
            String nombre = txtNombre.getText();
            String tipo = cbxTipoDeBarrera.getSelectedItem().toString();
            if (cbxAreaAProteger.isEnabled()) {
                area = cbxAreaAProteger.getSelectedItem().toString();
            } else {
                area = txtNombreDelArea.getText();
                String guar = cbxFactorOcupacion.getSelectedItem().toString();
                switch (guar) {
                    case "1":
                        factorOcupa = 1;
                        break;
                    case "1/2":
                        factorOcupa = (float) 0.5;
                        break;
                    case "1/5":
                        factorOcupa = (float) 0.2;
                        break;
                    case "1/20":
                        factorOcupa = (float) 0.05;
                        break;
                    case "1/40":
                        factorOcupa = (float) 0.025;
                        break;
                    default:
                        break;
                }
            }
            String disenoArea = cbxDisenioParaArea.getSelectedItem().toString();
            int imagenes = Integer.parseInt(cbxImagenesPorSemana.getSelectedItem().toString());
            int voltaje = Integer.parseInt(cbxVoltaje.getSelectedItem().toString());
            float distancia = Float.parseFloat(txtDistancia.getText());
            Barrera barrera = new Barrera(nombre, voltaje, imagenes, tipo, area, disenoArea, distancia);
            if (!(factorOcupa == 0)) {
                barrera.setFactorDeOcupacion(factorOcupa);
            }
            barrera.bp();
            barrera.setAcero(p.control.calculoAcero(barrera));
            barrera.setPlomo(p.control.calculoPlomo(barrera));
            barrera.setConcreto(p.control.calculoConcreto(barrera));
            JOptionPane.showMessageDialog(p, barrera.toString());
            p.control.agregarBarrera(barrera);
            btnCancelar.doClick();
            barrera = null;
            if(calculosRegistrados == null){
                calculosRegistrados = new CalculosRegistrados(p, control, this);
            }
            p.remove(this);
            p.add(calculosRegistrados, BorderLayout.CENTER);
            p.pack();
            p.setLocationRelativeTo(null);
            p.invalidate();
            p.revalidate();
            p.repaint();
        });
        btnOtro.addActionListener(f -> {
            if (cbxAreaAProteger.getSelectedItem().toString().equals("Otro")) {
                txtNombreDelArea.setEnabled(true);
                cbxFactorOcupacion.setEnabled(true);
                cbxAreaAProteger.setEnabled(false);
            }
        });
        btnCancelar.addActionListener(f ->{
            txtNombre.setText("");
            cbxTipoDeBarrera.setSelectedItem(null);
            cbxAreaAProteger.setSelectedItem(null);
            txtNombreDelArea.setText("");
            cbxFactorOcupacion.setSelectedItem(null);
            cbxDisenioParaArea.setSelectedItem(null);
            cbxImagenesPorSemana.setSelectedItem(null);
            cbxVoltaje.setSelectedItem(null);
            txtDistancia.setText("");
        });
    }
    @Override
    public void paintComponent (Graphics g){
        super.paintComponent(g);
        g.drawImage(Modelo.ImageLoader.resizeToFit(ImageLoader.cargarSprites("ImagenFondo/Fondo.jpg"), new Dimension(420, 600)),0,0, null);
        repaint();
    }
    
    
}
