/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.BorderLayout;

import javax.swing.UIManager;

import Modelo.Control;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author juanc
 */
public class Principal extends javax.swing.JFrame {
    InicioDeSesion inicio;
    Control control;
    /**
     * Creates new form Principal
     * @param control
     */
    public Principal(Control control) {
        initComponents();
        this.control = control;
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());
        try {

            UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");

        } catch (Exception ex) {

            ex.printStackTrace();

        }
        inicio = new InicioDeSesion(this, control);
        add(inicio, BorderLayout.CENTER);
//        setResizable(false);
        pack();
        setIconImage(Modelo.ImageLoader.cargarImagen("Vista/Logo.jpeg"));
        setTitle("RadControl S.A.S");
        onClose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Control getControl() {
        return control;
    }

    public void setControl(Control control) {
        this.control = control;
    }

    /**
     */
    
        
    public void onClose() {

		addWindowListener(new WindowAdapter() {

			@Override
			public void windowClosing(WindowEvent we) {

				String[] options = {"Salir", "Cancelar"};

				int ans = JOptionPane.showOptionDialog(null, "Seguro que desea salir?", "Salir",
						JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
				switch (ans) {
				case 0:
                                    dispose();
                                    setVisible(false);
                                    System.exit(0);
                                    break;
                                default:
                                    break;
				}
			}
		});
	}    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
